config/routes.rb
Rails.application.routes.draw do
  get 'users/home'

  get 'admins/home'

  get 'admin', to: 'admins#home'

  get 'users/browse_steps'

  get 'start/index'
  get 'start/about'
  get 'start/contact'

  resources :action_status, only: [:create, :update]
  resources :action_steps
  resources :questions

  root 'start#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }

end

app/models/action_step.rb
class ActionStep
  include Neo4j::ActiveNode
  property :title, type: String
  property :description, type: String
  property :level, type: Integer
  has_many :in, :users, rel_class: ActionStatus, unique: true

  validates :level, inclusion: 1..9, allow_nil: true

  def status_for_user(user)
    return nil if user.nil?
    user.action_steps.first_rel_to self
  end

  def self.sample
    (1..9).map do |level|
      ActionStep.where(level: level).first
    end.compact!
  end
end

app/controllers/action_steps_controller.rb
class ActionStepsController < ApplicationController
  before_action :set_step, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!,
                only: [:new, :edit, :create, :update, :destroy]

  # GET /steps
  # GET /steps.json
  def index
    @action_steps = ActionStep.all
  end

  # GET /steps/1
  # GET /steps/1.json
  def show
  end

  # GET /steps/new
  def new
    @action_step = ActionStep.new
  end

  # GET /steps/1/edit
  def edit
  end

  # POST /steps
  # POST /steps.json
  def create
    @action_step = ActionStep.new(step_params)
    respond_to do |format|
      if @action_step.save
        format.html do
          redirect_to @action_step, notice: 'Step was successfully created.'
        end
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /steps/1
  # PATCH/PUT /steps/1.json
  def update
    respond_to do |format|
      if @action_step.update(step_params)
        format.html do
          redirect_to @action_step,
                      notice: 'Step was successfully updated.'
        end
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /steps/1
  # DELETE /steps/1.json
  def destroy
    @action_step.destroy
    respond_to do |format|
      format.html do
        redirect_to steps_url,
                    notice: 'Step was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_step
    @action_step = ActionStep.find(params[:id])
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def step_params
    params.require(:action_step).permit(:title, :description, :level)
  end
end

app/helpers/action_steps_helper.rb
module ActionStepsHelper
end

app/views/action_steps/_card.html.erb
<%= content_tag :div, class: 'col-md-6' do %>
    <%= content_tag :div, class: 'well subtle' do %>
        <%= content_tag :h2, step.title %>
        <%= content_tag :h3,  "Svårighetsgrad: #{step.level}" %>
        <p><%= step.description %> </p>
        <% action_status = step.status_for_user current_user %>
        <%= change_status_link(action_status, step) %>
    <% end %>
<% end %>

app/views/action_steps/_form.html.erb
<%= form_for(@action_step) do |f| %>
  <% if @action_step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@action_step.errors.count, "error") %> prohibited this action step from being saved:</h2>

      <ul>
      <% @action_step.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :level %><br/>
    <%= f.select :level, 1..9 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= render 'action_steps/partials/level_descriptions' %>

app/views/action_steps/edit.html.erb
<h1>Editing Step</h1>

<%= render 'form' %>

<%= link_to 'Show', @action_step %> |
<%= link_to 'Back', action_steps_path %>

app/views/action_steps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Action steps</h1>
<table class="table">
  <tbody>
    <% @action_steps.each do |step| %>
      <tr>
        <td><%= step.title %></td>
        <td><%= step.description %></td>
        <td><%= step.level %></td>
        <td><%= link_to 'Show', step %></td>
        <td><%= link_to 'Edit', edit_action_step_path(step) %></td>
        <td><%= link_to 'Destroy', step, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Step', new_action_step_path %>
<%= render 'action_steps/partials/level_descriptions' %>
<br>

app/views/action_steps/new.html.erb
<h1>New Step</h1>

<%= render 'form' %>

<%= link_to 'Back', action_steps_path %>

app/views/action_steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @action_step.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @action_step.description %>
</p>

<p>
  <strong>Level:</strong>
  <%= @action_step.level %>
</p>

<%= link_to 'Edit', edit_action_step_path(@action_step) %> |
<%= link_to 'Back', action_steps_path %>