config/routes.rb
Rails.application.routes.draw do
  get 'users/home'

  get 'admins/home'

  get 'admin', to: 'admins#home'

  get 'users/browse_steps'

  get 'start/index'
  get 'start/about'
  get 'start/contact'

  resources :action_status, only: [:create, :update]
  resources :action_steps
  resources :questions

  root 'start#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }

end

app/controllers/start_controller.rb
class StartController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/helpers/start_helper.rb
module StartHelper
end

app/views/start/about.html.erb
<div class="row">
  <div>
    <h1>Om Omidorido</h1>
    <p>
      Omidorido är en hemsida för dig som vill minska din miljöpåverkan.
      Miljötips erbjuds av många, men ingen som möter dig just där du är.
      Omidorido filtrerar bort det som inte är relevant för dig och serverar resten i den ordning som passar dig bäst,
      med möjlighet att tydligt se framstegen.
    </p>
  </div>
  <div>
  <h2>Tidsplan</h2>
  <p>
   Just nu är Omidorido i en pre-beta fas. Om du vill ha ett konto kan du maila <%= mail_to 'konto@omidorido.se' %> för
    för kunna bli del av vårt pre-beta-program.
  </p>
  </div>
  <div>
    <h2>Uppdateringar</h2>
    <dl>
     <dt>22/2</dt><dd>Första versionen.</dd>
    </dl>
  </div>

</div>

app/views/start/contact.html.erb
<div>
<h1>Kontakta oss</h1>
<p>Om du har tankar, förslag, frågor eller vill meddela oss något annat går det bra att maila
    <%= mail_to 'kontakt@omidorido.se' %> </p>
<p>Jag som driver omidorido.se heter Ester Ytterbrink</p>
</div>

app/views/start/index.html.erb
<h1><%= t('home.index.header') %></h1>
<div class="row">
    <div class="col-md-3">
      <div class="well subtle">
        <%= link_to t('home.index.my_stuff'), users_home_path %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="well subtle">
        <%= link_to t('home.index.steps_to_take'), users_browse_steps_path %>
      </div>
    </div>
</div>