config/routes.rb
Rails.application.routes.draw do
  get 'users/home'

  get 'admins/home'

  get 'admin', to: 'admins#home'

  get 'users/browse_steps'

  get 'start/index'
  get 'start/about'
  get 'start/contact'

  resources :action_status, only: [:create, :update]
  resources :action_steps
  resources :questions

  root 'start#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Omidorido" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
      <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">

          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Omidorido</a>
          <div class="navbar-collapse collapse navbar-responsive-collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to t('common.contact'), start_contact_path  %></li>
              <li><%= link_to t('common.about'), start_about_path  %></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="col-md-3">
            <div class="well sidebar-nav">
              <h3><%=t('common.user_header')%></h3>
              <ul class="nav nav-list">
                <%= content_tag(:li, I18n.t('common.current_user', {user: current_user.email}), class:'nav-header') unless current_user.nil? %>
                <%= content_tag(:li, link_to(I18n.t('common.log_in'), new_user_session_path)) if current_user.nil? %>
                <%= content_tag(:li, link_to(I18n.t('common.log_out'), destroy_user_session_path, method: 'delete')) unless current_user.nil? %>
                <hr/>
                <%= content_tag(:li, I18n.t('common.current_user', {user: current_admin.email}), class:'nav-header') unless current_admin.nil? %>
                <%= content_tag(:li, link_to(I18n.t('common.log_out'), destroy_admin_session_path, method: 'delete')) unless current_admin.nil? %>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->
      </div> <!-- /container -->
    <footer class="footer">
      <div class="container">
        <p class="padded">&copy; Ester Ytterbrink 2015</p>
      </div>
    </footer>
  </body>
</html>